PREFIX dbpedia: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dbprop: <http://dbpedia.org/property/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX geoes: <http://geo.linkeddata.es/ontology/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ex: <http://example.com/>  
  
SELECT ?company ?label WHERE {
#	SERVICE <http://mappingpedia.linkeddata.es/mappings/fusiontables/1i77i0TCZG65tH4xEgTyszwD_w3oXUfq7dkK8Ejk/BeerCompanies.ttl> {
		?company rdf:type <http://dbpedia.org/ontology/Company> .
		?company rdfs:label ?label .
#	}
} 
